image: rainu/docker-node

stages:
  - test
  - dockerize

backend-test:
  stage: test
  script:
    - apk --update add git
    - cd backend
    - npm install
    - npm run test

dockerize-backend:
  stage: dockerize
  script:
    - apk --update --no-cache add docker
    - cd backend
    - docker build . -t rainu/allmyforks-backend
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker push rainu/allmyforks-backend
  only:
    - master
