image: rainu/docker-node

stages:
  - dockerrize

dockerrize-crawler:
  image: tmaier/docker-compose:latest
  stage: dockerrize
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - cd crawler
    # it doesn't matter what a crawler we choose: all crawler have the same Dockerfile
    - docker-compose build crawler_coinmarketcap
    - docker-compose push crawler_coinmarketcap
  only:
    - master
