version: '3'
services:

  crawler_fiat:
    image: rainu/cryptocrawler
    build:
      context: ./
    environment:
      - CFG_MONGO_HOST=db
      - CFG_MONGO_DB=fiat
      - CFG_CRON=0 0 */12 * * *
    command: "fiat.js"
    restart: always
    depends_on:
      - db

  crawler_coinmarketcap:
    image: rainu/cryptocrawler
    build:
      context: ./
    environment:
      - CFG_MONGO_HOST=db
      - CFG_MONGO_DB=coinmarketcap
      - CFG_CRON=0 0 */4 * * *
    command: "coinmarketcap.js"
    restart: always
    depends_on:
      - db

  crawler_bitfinex:
    image: rainu/cryptocrawler
    build:
      context: ./
    environment:
      - CFG_MONGO_HOST=db
      - CFG_MONGO_DB=bitfinex
      - CFG_CRON=0 0 */4 * * *
    command: "bitfinex.js"
    restart: always
    depends_on:
      - db

  ticker_bitfinex:
    image: rainu/cryptocrawler
    build:
      context: ./
    environment:
      - CFG_MONGO_HOST=db
      - CFG_MONGO_DB=bitfinex
    command: "bitfinex_ticker.js"
    restart: always
    depends_on:
      - db

  crawler_binance:
    image: rainu/cryptocrawler
    build:
      context: ./
    environment:
      - CFG_MONGO_HOST=db
      - CFG_MONGO_DB=binance
      - CFG_CRON=0 0 */4 * * *
    command: "binance.js"
    restart: always
    depends_on:
      - db

  crawler_okex:
    image: rainu/cryptocrawler
    build:
      context: ./
    environment:
      - CFG_MONGO_HOST=db
      - CFG_MONGO_DB=okex
      - CFG_CRON=0 0 */4 * * *
    command: "okex.js"
    restart: always
    depends_on:
      - db

  crawler_coinbase:
    image: rainu/cryptocrawler
    build:
      context: ./
    environment:
      - CFG_MONGO_HOST=db
      - CFG_MONGO_DB=coinbase
      - CFG_JOB_0_SYMBOL=BTC
      - CFG_JOB_0_CRON=0 0 */4 * * *
      - CFG_JOB_1_SYMBOL=BCH
      - CFG_JOB_1_CRON=0 0 */4 * * *
      - CFG_JOB_2_SYMBOL=ETH
      - CFG_JOB_2_CRON=0 0 */4 * * *
      - CFG_JOB_3_SYMBOL=LTC
      - CFG_JOB_3_CRON=0 0 */4 * * *
    command: "coinbase.js"
    restart: always
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - ./db:/data/db
    restart: always

###################
#
# AGGREGATOR
#

  course_aggregator:
    image: rainu/cryptoaggregator
    build:
      context: ../aggregator/course
    environment:
      - CFG_SOURCE_0_URL=mongodb://db/coinmarketcap
      - CFG_SOURCE_0_NAME=coinmarketcap.com
      - CFG_SOURCE_1_URL=mongodb://db/bitfinex
      - CFG_SOURCE_1_NAME=bitfinex.com
      - CFG_SOURCE_2_URL=mongodb://db/binance
      - CFG_SOURCE_2_NAME=binance.com
      - CFG_SOURCE_3_URL=mongodb://db/coinbase
      - CFG_SOURCE_3_NAME=coinbase.com
      - CFG_SOURCE_4_URL=mongodb://db/fiat
      - CFG_SOURCE_4_NAME=fiat
      - CFG_SOURCE_5_URL=mongodb://db/okex
      - CFG_SOURCE_5_NAME=okex.com
    command: "server.js"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db